### ISSUE TITLE
Invalid hexadecimal integer literal without gawk package

### ISSUE THREAD

**Issue by adrianjuszczak** [nxp-auto-linux/arm-trusted-firmware#1]
After building the Arm Trusted Firmware for target s32g274ardb2. 
Source file located in arm-trusted-firmware/build/s32g274ardb2/release/boot_info.c contains following line.

const unsigned long fip_mmc_offset = 0x - which I assume is invalid hexadecimal integer.

After gawk package installation, compilation problem ceases? Is it expected?

Regards 
Adrian

**Comment by catalinudmanxp** [comment]
gawk is mandatory, see https://github.com/nxp-auto-linux/arm-trusted-firmware/blob/release/bsp38.0-2.5/plat/nxp/s32/s32_common.mk#L21
